### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Hatrickek** [Hatrickek/Mavreas-Engine#2]
- [x] Working gizmos.
- [ ] Gizmo icons.
- [x] Fix the rotation issue on Transform Component.
- [ ] Logger print to in-app GUI console too.
- [ ] Mouse picking.
- [x] Cmake.
- [x] Content browser.
- [ ] Save/Load imgui window layouts.
- [x] Lighting abstraction.
- [ ] Audio playback.

**Comment by yunusterzi** [comment]
7 Ağu 2022 Paz, saat 14:45 tarihinde Halim ***@***.***> şunu
yazdı:
